### ISSUE TITLE
Tensorboard just freeze

### ISSUE THREAD

**Issue by Freshield** [normanheckscher/mnist-tensorboard-embeddings#2]
Hello, when I run the mnist_with_summaries.py and run tensorboard after, everything is fine but the embedding page will freeze, the page says fetching sprite image and circle loop forever.
![2017-04-04 15-29-41](https://cloud.githubusercontent.com/assets/15166014/24675001/8d5125cc-194b-11e7-82b9-7ca67855f678.png)

**Comment by normanheckscher** [comment]
Does mnist_t-sne.py work?

**Comment by Freshield** [comment]
Nope, the same thing
![2017-04-04 15-39-16](https://cloud.githubusercontent.com/assets/15166014/24675379/edd11032-194c-11e7-82ee-d550178bc1cf.png)

**Comment by Freshield** [comment]
And what I changed just the log position
![2017-04-04 15-40-34](https://cloud.githubusercontent.com/assets/15166014/24675414/0f4e44c8-194d-11e7-8b6e-023b5a63b5cb.png)

**Comment by Freshield** [comment]
And if I delete the whole logs folder, only run the mnist_with_summaries.py, it will meet an error say can not find logs/projector/metadata.tsv, but after I create a projector folder in logs then it works, so maybe the folder creation code also miss

**Comment by normanheckscher** [comment]
This reads like your interpreter is searching for the sprite file which is located in the mnist_data directory.

https://github.com/normanheckscher/mnist-tensorboard-embeddings/blob/master/mnist_data/mnist_10k_sprite.png

**Comment by Freshield** [comment]
Yep, I also find it, ahah, thank you very much, it works when I download it, so it can't generate by the code itself?

**Comment by ethanabrooks** [comment]
I am experiencing the same issue and I have downloaded the full repo:
```
❯ tree
.
├── data
│   ├── t10k-images-idx3-ubyte.gz
│   ├── t10k-labels-idx1-ubyte.gz
│   ├── train-images-idx3-ubyte.gz
│   └── train-labels-idx1-ubyte.gz
├── LICENSE.md
├── logs
│   └── projector
│       ├── a_model.ckpt-10000.data-00000-of-00001
│       ├── a_model.ckpt-10000.index
│       ├── a_model.ckpt-10000.meta
│       ├── checkpoint
│       ├── events.out.tfevents.1544190075.omen
│       ├── metadata.tsv
│       └── projector_config.pbtxt
├── mnist_data
│   └── mnist_10k_sprite.png
├── mnist_t-sne.py
├── mnist_with_summaries.py
├── README.md
└── tests
    └── test_example.py
```
I run 
```
python mnist_t-sne.py --log_dir="$HOME/mnist-tensorboard-embeddings/logs" --data_dir="$HOME/mnist-tensorboard-embeddings/data"
```
Then
```
tensorboard --logdir="$HOME/mnist-tensorboard-embeddings/logs"
```
The program hangs at "Fetching sprite image...".

Python 3.6.5
tensorboard==1.8.0
tensorflow==1.8.0


# Update
The issue is that the `--data_dir` flag has to point to `"$HOME/mnist-tensorboard-embeddings/mnist_data"`

Would recommend removing the flag and hard-coding the path using `__file__`.
