### ISSUE TITLE
metadata.tsv missing

### ISSUE THREAD

**Issue by Spenhouet** [normanheckscher/mnist-tensorboard-embeddings#3]
I just wanted to start your `mnist_with_summaries.py` example but i get the following error:

`No such file or directory: 'C:/tmp/tensorflow/logs/projector/metadata.tsv'`

I guess the `metadata.tsv` file should be in the `logs/projector` directory but I can't find this file in your repository.
Where do i get this file from or how to generate it?

**Comment by normanheckscher** [comment]
It should be generated when the script is run.

Here is the function:

https://github.com/normanheckscher/mnist-tensorboard-embeddings/blob/master/mnist_with_summaries.py#L212

**Comment by Spenhouet** [comment]
The problem was that the `projector` folder wasn't created. I had to create it manually. The code should probably take care of this.

**Comment by normanheckscher** [comment]
The folder already exists in the code base. Download the entire tar ball or use git to pull the code.

**Comment by Spenhouet** [comment]
Only if the code is in this folder: `/Users/norman/Documents/workspace/mnist-tensorboard-embeddings/`
What is a wrong folder itself.
Wouldn't it be easier to just store and generate everything in a `/tmp/` sub folder with auto creation of every folder so you only need to start the python file without initiating anything else?
I'm just saying, there is room for improvement.

**Comment by normanheckscher** [comment]
Create a pull request.

**Comment by Spenhouet** [comment]
I ended up not using this example nn. Therefore I will probably not create a pull request.
Just thought I give you feedback on this.
